### PR TITLE
show open workspace settings icon in explorer when possible

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by dannywrayuk** [comment]
Hey, thanks a lot for your contribution!

I like this, however my only remark would be that adding this button to the `view/title` will shift the rest of the buttons and throw off my muscle memory for the `Collapse All` which I use white a lot when working with workspaces. If you added this to the right click menu I'd be more inclined to approve.

Also just wondering what your motivation for this is? There is no button to open the regular settings, is there any reason you think we need one for workspace settings? I though the keyboard shortcut `cmd`+`shift`+`,` to parallel the existing `cmd`+`,` for the regular settings was enough?

**Comment by ctf0** [comment]
for me all the icons are visible 
Screen Shot 2023-05-09 at 4 29 37 PM

as for the shortcut, i prefer buttons when possible so i dont have to remember the million shortcut i use daily

**Comment by dannywrayuk** [comment]
It's great that it doesn't shift the icons, I'm more convinced since I've seen that. However I'd have to disagree with you, I don't like adding random buttons to the UI!

Thats a perfectly valid opinion though, so maybe this extension might be something you're interested in?
https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar

**Comment by ctf0** [comment]
> so maybe this extension might be something you're interested in?

thats different, but np, i can keep it as a local enhancement

**Pull request closed without merging**
